name: Build Blood Donor System CI

on:
  pull_request:
    branches:
      - "main"

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_USER: milos
          POSTGRES_PASSWORD: password
          POSTGRES_DB: bds
        ports:
          - 5332:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Test PostgreSQL Connection
        run: psql -h localhost -U milos -d bds -p 5332 -W

      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Insert data into PostgreSQL database
        env:
          POSTGRES_USER: milos
          POSTGRES_PASSWORD: password
          POSTGRES_DB: bds
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5332
        run: |
          PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_DB -p $POSTGRES_PORT -c "
          CREATE TABLE IF NOT EXISTS users (
            id BIGSERIAL PRIMARY KEY, 
            first_name TEXT NOT NULL, 
            last_name TEXT NOT NULL, 
            email TEXT NOT NULL UNIQUE, 
            role TEXT NOT NULL CHECK (role in ('ADMIN', 'DONOR')),
            blood_type TEXT not null CHECK (
              blood_type in ('APos', 'ANeg', 'BPos', 'BNeg', 'ABPos', 'ABNeg', 'OPos', 'ONeg'))
          );
          
          INSERT INTO users (first_name, last_name, email, role, blood_type) 
          VALUES ('milos', 'b', 'milos@gmail.com', 'ADMIN', 'APos');
          " 

      - name: Build and run Unit/Integration Test with Maven
        run: mvn -ntp -B verify